export const schemas = {
  User: {
    type: "object",
    properties: {
      id: { type: "integer" },
      username: { type: "string" },
      email: { type: "string" },
      password: { type: "string" },
      role: { type: "string" },
      registeredAt: { type: "string", format: "date-time" },
      hasPurchased: { type: "boolean" },
    },
  },
  Instructor: {
    type: "object",
    properties: {
      id: { type: "integer" },
      userId: { type: "integer" },
    },
  },
  Course: {
    type: "object",
    properties: {
      id: { type: "integer" },
      title: { type: "string" },
      imageSrc: { type: "string" },
      instructorId: { type: "integer" },
      category: { type: "string" },
      price: { type: "integer" },
      visits: { type: "integer" },
      description: { type: "string" },
      level: { type: "string" },
    },
  },
  Video: {
    type: "object",
    properties: {
      id: { type: "integer" },
      courseId: { type: "integer" },
      title: { type: "string" },
      videoUrl: { type: "string" },
      duration: { type: "string" },
      thumbnailUrl: { type: "string" },
      order: { type: "integer" },
    },
  },
  Unit: {
    type: "object",
    properties: {
      id: { type: "integer" },
      title: { type: "string" },
      description: { type: "string" },
      courseId: { type: "integer" },
      order: { type: "integer" },
    },
  },
  Lesson: {
    type: "object",
    properties: {
      id: { type: "integer" },
      title: { type: "string" },
      unitId: { type: "integer" },
      order: { type: "integer" },
    },
  },
  Challenge: {
    type: "object",
    properties: {
      id: { type: "integer" },
      type: { type: "string", enum: ["SELECT", "ASSIST"] },
      question: { type: "string" },
      lessonId: { type: "integer" },
      order: { type: "integer" },
    },
  },
  ChallengeOption: {
    type: "object",
    properties: {
      id: { type: "integer" },
      challengeId: { type: "integer" },
      text: { type: "string" },
      correct: { type: "boolean" },
      imageSrc: { type: "string" },
      audioSrc: { type: "string" },
    },
  },
  ChallengeProgress: {
    type: "object",
    properties: {
      id: { type: "integer" },
      userId: { type: "string" },
      challengeId: { type: "integer" },
      completed: { type: "boolean" },
    },
  },
  UserProgress: {
    type: "object",
    properties: {
      userId: { type: "string" },
      userName: { type: "string" },
      userImageSrc: { type: "string" },
      activeCourseId: { type: "integer" },
      hearts: { type: "integer" },
      points: { type: "integer" },
    },
  },
  LiveStream: {
    type: "object",
    properties: {
      id: { type: "integer" },
      instructorId: { type: "integer" },
      title: { type: "string" },
      date: { type: "string", format: "date" },
      category: { type: "string" },
      price: { type: "integer" },
      ingressId: { type: "string" },
      serverUrl: { type: "string" },
      streamKey: { type: "string" },
      isLive: { type: "boolean" },
      isChatEnabled: { type: "boolean" },
      isChatDelayed: { type: "boolean" },
      isChatFollowersOnly: { type: "boolean" },
    },
  },
  Leaderboard: {
    type: "object",
    properties: {
      userId: { type: "integer" },
      type: { type: "string" },
      period: { type: "string" },
      points: { type: "integer" },
    },
  },
  Ticket: {
    type: "object",
    properties: {
      id: { type: "integer" },
      guidanceId: { type: "integer" },
      userId: { type: "string" },
      row: { type: "string" },
      column: { type: "integer" },
      purchasedAt: { type: "string", format: "date-time" },
      isBooked: { type: "boolean" },
    },
  },
  Sale: {
    type: "object",
    properties: {
      id: { type: "integer" },
      userId: { type: "integer" },
      courseId: { type: "integer" },
      streamId: { type: "integer" },
      amount: { type: "integer" },
    },
  },
  UserSubscription: {
    type: "object",
    properties: {
      id: { type: "integer" },
      userId: { type: "string" },
      stripeCustomerId: { type: "string" },
      stripeSubscriptionId: { type: "string" },
      stripePriceId: { type: "string" },
      stripeCurrentPeriodEnd: { type: "string", format: "date-time" },
    },
  },
  UserQuest: {
    type: "object",
    properties: {
      userId: { type: "integer" },
      id: { type: "integer" },
      title: { type: "string" },
      description: { type: "string" },
      rewardPoints: { type: "integer" },
      progress: { type: "integer" },
    },
  },
  LanguageProgress: {
    type: "object",
    properties: {
      userId: { type: "integer" },
      username: { type: "string" },
      languageId: { type: "integer" },
      languageName: { type: "string" },
      progress: { type: "integer" },
    },
  },
  Guidance: {
    type: "object",
    properties: {
      id: { type: "integer" },
      instructorId: { type: "integer" },
      name: { type: "string" },
      description: { type: "string" },
      price: { type: "number" },
      durationInHours: { type: "integer" },
      createdAt: { type: "string", format: "date-time" },
      updatedAt: { type: "string", format: "date-time" },
    },
  },
};
